### PR TITLE
Update Plugin.php

### PR DESCRIPTION
**Pull request by X3msnake**
The right code is &rel=0 instead of ?rel=0

rel=0 is used to show no related videos after the end of the ebbeded movie...

Also using ?rel=0 as is breaks the possibility of the user using start times in the ebbeded markdown like;

youtube=LyemmoPBOUY?start=302

### CODE REVIEW

**Comment by Schlaefer** [comment]
The plugin depends on getting the raw video-ID at the moment, because the ID is also used to query an additional API to retrieve the video title. 

So `youtube=<id>[?<additional params>]` is not possible by changing only this spot in the code. Another issue is that the generated URL isn't valid if the user doesn't add the `?` manually.

To make this work the plugin has to split up the part right from the `=` into ID and additional params and glue it together again at the end.

PS: I suggest to consider the great [snippet plugin](https://github.com/infostreams/snippets) which also has youtube embedding out of the box and offers easy custom snippets with additional parameter.

**Comment by X3msnake** [comment]
You can see it working here Master
http://altlab.org/d/

The code dosen't need ?rel=0 at all.

that code is malformed as is, if you use it like that it will produce no result on the video.

see here a wp discussion about this
https://wordpress.org/support/topic/embed-youtube-and-not-show-related-videos-when-video-is-finished

**Comment by X3msnake** [comment]
You'r right sorrry, 

But, the ?rel=0 can be removed all together...

you can see these changes working at our Documenta Project 

http://altlab.org/d/m/x3msnake/

/// https://developers.google.com/youtube/player_parameters#Manual_IFrame_Embeds
Loading a video

http://www.youtube.com/embed/VIDEO_ID

**Comment by Schlaefer** [comment]
I think "rel=0" is good default to have.

I updated the code to make the "rel" a config param and also allow other params (like "start"). Please check out if it works for you.

**Comment by X3msnake** [comment]
Perfect Master @Schlaefer 

Thank You for your dedication ;)

**Pull request closed without merging**
